apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: jenkins
spec:
  project: default
  source:
    repoURL: 'https://github.com/Osher2010/argo_jenkins.git'
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyApp
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 3  
  selector:
    matchLabels:
      app:  jenkinsapp
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: OsherAPP  
          ports:
            - containerPort: 80
          env:
            - name: ENV
              value: "development"  
          resources:  
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: <NAMESPACE>
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer 
